changes test reporter

diff --git a/.github/workflows/client_web.ci.yml b/.github/workflows/client_web.ci.yml
--- a/.github/workflows/client_web.ci.yml
+++ b/.github/workflows/client_web.ci.yml
@@ -1,4 +1,4 @@
-name: Run tests on push to feature branches if changes to client_web
+name: client_web CI
 
 on:
   push:
@@ -21,8 +21,11 @@ jobs:
         run: cd client_web && yarn install --immutable
 
       - name: Run tests
-        run: cd client_web && yarn run test
+        run: cd client_web && yarn run ci-test
 
-      - name: Publish Unit Test Results
-        uses: EnricoMi/publish-unit-test-result-action@v1.23
-        if: always()
+      - name: Upload Test Results
+          uses: actions/upload-artifact@v2  # upload test results
+          if: success() || failure()        # run this step even if previous step failed
+            with:
+              name: test-output
+              path: client_web/test-output.json
